---
abstract: 'A cart/order/checkout framework with AxKit/TT/Catalyst support'
author:
  - 'Christopher H. Laco'
build_requires:
  Test::More: 0.61
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Handel
no_index:
  directory:
    - inc
    - t
    - demo
requires:
  Carp: 0
  Class::Accessor::Grouped: 0.03
  Class::ISA: 0
  Class::Inspector: 0
  Clone: 0.28
  DBD::SQLite: 0
  DBIx::Class: 0.08008
  DBIx::Class::UUIDColumns: 0.02000
  DBIx::Class::Validation: 0.02000
  Data::Currency: 0.04002
  DateTime: 0
  DateTime::Format::MySQL: 0
  Error: 0.14
  File::Path: 0
  File::Spec::Functions: 0
  FileHandle: 0
  Finance::Currency::Convert::WebserviceX: 0.03
  FormValidator::Simple: 0.17
  Getopt::Long: 0
  Locale::Currency: 2.07
  Locale::Currency::Format: 1.22
  Locale::Maketext: 1.06
  Module::Pluggable: 3.1
  Module::Starter: 1.42
  NEXT: 0
  Pod::Usage: 0
  SQL::Translator: 0.08
  Scalar::Util: 0
  Tie::Hash: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 1.00011
