# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Handel
version:      0.03
version_from: lib/Handel.pm
installdirs:  site
license:      perl
requires:
    Class::DBI:                    0.96
    DBI:                           1.36
    Error:                         0.14
    Locale::Maketext:              1.06
    Test::More:                    0.48

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
