--- #YAML:1.0
name: Handel
abstract: Simple commerce framework with AxKit/TT2 support
author: Christopher H. Laco <claco@chrislaco.com>
version: 0.14
version_from: lib/Handel.pm
installdirs: site
license: perl
requires:
  Class::DBI: 0.96
  DBI: 1.36
  Error: 0.14
  Locale::Maketext: 1.06
recommends:
  AxKit: 1.62
  Locale::Currency::Format: 1.22
  Pod::Coverage: 0.14
  Template: 2.14
  Test::More: 0.48
  Test::Pod: 1.00
  Test::Pod::Coverage: 1.04
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
