---
abstract: 'A cart/order/checkout framework with AxKit/TT/Catalyst support'
author:
  - 'Christopher H. Laco'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Handel
no_index:
  directory:
    - demo
    - inc
    - t
requires:
  Carp: 0
  Catalyst::Devel: 1.28
  Catalyst::Plugin::Session: 0.3
  Catalyst::Plugin::Session::State::Cookie: 0.17
  Catalyst::Plugin::Session::Store::File: 0.18
  Catalyst::Runtime: 5.80025
  Catalyst::View::TT: 0.34
  Class::Accessor::Grouped: 0.09003
  Class::ISA: 0.36
  Class::Inspector: 1.24
  Clone: 0.31
  DBD::SQLite: 1.29
  DBIx::Class: 0.08123
  DBIx::Class::UUIDColumns: 0.02005
  DBIx::Class::Validation: 0.02005
  Data::Currency: 0.04002
  DateTime: 0.61
  DateTime::Format::MySQL: 0.04
  Error: 0.17016
  File::Path: 2.08
  File::Spec::Functions: 3.3
  FileHandle: 2.01
  Finance::Currency::Convert::WebserviceX: 0.07001
  FormValidator::Simple: 0.28
  Getopt::Long: 2.38
  HTML::FillInForm: 2.00
  Locale::Currency: 2.07
  Locale::Currency::Format: 1.28
  Locale::Maketext: 1.13
  Module::Pluggable: 3.9
  Module::Starter: 1.54
  NEXT: 0.64
  Pod::Usage: 1.36
  SQL::Translator: 0.11006
  Scalar::Util: 1.22
  Tie::Hash: 1.03
  YAML: 0.71
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 1.00012
