--- #YAML:1.0
name: Handel
abstract: Simple commerce framework with AxKit/TT/Catalyst support
author: Christopher H. Laco <claco@chrislaco.com>
version: 0.99_07
version_from: lib/Handel.pm
installdirs: site
license: perl
requires:
  DBIx::Class: 0.08
  DBIx::Class::UUIDColumns: 0
  DBIx::Class::Validation: 0
  Class::Accessor::Grouped: 0.02
  Class::ISA: 0
  Class::Inspector: 0
  Clone: 0
  Error: 0.14
  Locale::Maketext: 1.06
  Module::Pluggable: 2.95
  Scalar::Util: 0
  Tie::Hash: 0
  DateTime: 0
  DateTime::Format::MySQL: 0
build_requires:
  Test::More: 0.61
recommends:
  AxKit: 1.61
  Catalyst::Runtime: 5.7001
  Catalyst::Devel: 1.0
  FormValidator::Simple: 0.16
  HTML::FillInForm: 1.04
  Finance::Currency::Convert::WebserviceX: 0.03
  Locale::Currency::Format: 1.22
  Locale::Currency: 2.07
  Pod::Coverage: 0.14
  Template: 2.14
  YAML: 0.58
  Test::Pod: 1.00
  Test::Pod::Coverage: 1.04
  Test:Strict: 0.05
  Test::Spelling: 0.10
  Test::NoTabs: 0.01
  Test::Perl::Critic: 0.07
no_index:
  directory:
    - demo
    - sql
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
