--- #YAML:1.0
name: Handel
abstract: Simple commerce framework with AxKit/TT2 support
author: Christopher H. Laco <claco@chrislaco.com>
version: 0.16_02
version_from: lib/Handel.pm
installdirs: site
license: perl
requires:
  Class::DBI: 0.96
  DBI: 1.36
  Error: 0.14
  Locale::Maketext: 1.06
  Module::Pluggable: 2.8
build_requires:
  Test::More: 0.48
recommends:
  AxKit: 1.61
  Finance-Currency-Convert-WebserviceX: 0.03
  Locale::Currency::Format: 1.22
  Locale::Currency: 2.07
  Pod::Coverage: 0.14
  Template: 2.14
  Test::Pod: 1.00
  Test::Pod::Coverage: 1.04
  Test:Strict: 0.05
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
